### ISSUE TITLE
iso_date can cause 500 error upon invalid input

### ISSUE THREAD

**Issue by Rogierownage** [Intervention/validation#19]
ErrorException(code: 0): preg_match() expects parameter 2 to be string, array given at vendor/intervention/validation/src/Intervention/Validation/Validator.php:322

If the data supplied is an array instead of a string, you get this error. Ideally, it should return false instead, if the data is not a string.

**Comment by olivervogel** [comment]
Fixed in [1.4.1](https://github.com/Intervention/validation/releases/tag/1.4.1).
