### ISSUE TITLE
The key 'password' in the language files conflicts with the default language files of Laravel

### ISSUE THREAD

**Issue by madman-81** [Intervention/validation#27]
See https://github.com/laravel/laravel/blob/master/resources/lang/en/validation.php

Laravel already has a key 'password' in its default data set. It translates to 'The password is incorrect'.

Caouecs has also used the same key for the same meaning in his translations (see https://github.com/caouecs/Laravel-lang).

I would like to suggest to use another key for the password validation. Maybe something like 'password_length' or 'strong_password'.

**Comment by olivervogel** [comment]
Thanks, I think my function was not sufficient for checking the password strength. Having numbers or special characters in a password does not make it automatically [strong](https://blog.fleetsmith.com/password-security-guide/). Therefore I removed the password validation in the new version (2.0) of this package.
