### ISSUE TITLE
BIC Validation Issue

### ISSUE THREAD

**Issue by hofmannsven** [Intervention/validation#29]
I'm using the BIC validation and it works fine but I noticed that the BIC number `DEUTDBBER` is validated as valid, even though it seems to be an invalid BIC number:
https://transferwise.com/gb/swift-codes/bic-swift-code-checker?code=DEUTDBBER&direction=receive
Can you help?

**Comment by olivervogel** [comment]
You're right. The [regular expression](https://github.com/Intervention/validation/blob/master/src/Intervention/Validation/Validator.php#L216
) is actually wrong.

Should be:

```php
$pattern = "/^[A-Za-z]{4} ?[A-Za-z]{2} ?[A-Za-z0-9]{2} ?([A-Za-z0-9]{3})?$/";
```

It's a shame I didn't noticed this.

**Comment by hofmannsven** [comment]
Thank you very much for your help and fast response!

Is it possible to also release this patch for the 1.x version of the package? (see issue #30)

**Comment by hofmannsven** [comment]
Thank you!
