### ISSUE TITLE
Validation rule does not exist

### ISSUE THREAD

**Issue by hofmannsven** [Intervention/validation#30]
Since the 2.0.0-beta1 I'm having issues with my custom validation rules (see [using extensions](https://laravel.com/docs/5.8/validation#using-extensions)).

I added the custom validation rule right inside my app service provider:
```php
Validator::extend('foo', 'FooValidator@validate');
```

And I keep getting the error:
> Validation rule (Intervention\Validation\Rules\Foo) does not exist.

Can you help?

**Comment by olivervogel** [comment]
Well, It’s still beta. I suggest to stick to 1.x for now.

**Comment by hofmannsven** [comment]
Thanks for your reply. It already works with the 2.0.0-beta3.
