### ISSUE TITLE
How can I overwrite the messages?

### ISSUE THREAD

**Issue by PanManAms** [Intervention/validation#4]
Hi!
The package works great for validating IBAN numbers! Thanks!
However, is it possible to overwrite the message?
setting 
'iban'                  => 'De :attribute is geen geldig IBAN nummer',
in resources/lang/en/validation.php doesn't work, and neither does passing a custom message to a validator? This does work for the built-in validators.
Thanks!

**Comment by olivervogel** [comment]
I added the possibility to overwrite error messages in 79e0eb78ae6409dffda25d878adfd4499e51006f.

Add the corresponding key to `/resources/lang/<language>/validation.php` like this:

```php
// example
'iban' => 'Please enter IBAN number!',
```

Or add your custom messages [directly to the validator](http://laravel.com/docs/5.1/validation#custom-error-messages) like described in the docs.

**Comment by PanManAms** [comment]
Whow, thanks for the quick response! This works great!

**Comment by PanManAms** [comment]
I created a quick pull req to add this to the readme.
