### ISSUE TITLE
IBAN Validator Issue with ISO 3166-1 alpha-2 CR Costa Rica

### ISSUE THREAD

**Issue by jansgescheit** [Intervention/validation#46]
I'm testing my form request with phpfaker.

Now a form request test is flickering in which an Iban is validated. I found out that this always happens when [phpfaker](https://fakerphp.github.io/formatters/payment/#iban) generates an IBAN for Costa Rica. According to https://bank.codes/iban/structure/costa-rica/, the IBAN has 22 characters, but the validator [expects 21 characters](https://github.com/Intervention/validation/blob/268f3ea669f2a1e23eab56ab862a5c5217355ec4/src/Rules/Iban.php#L24).

**Comment by olivervogel** [comment]
Fixed in 2.6.7
