### ISSUE TITLE
Missing releases

### ISSUE THREAD

**Issue by williamdes** [Intervention/validation#52]
Hi,

Could you please write releases for new tags since the last release ?
There is no CHANGELOG and this is blocking me to understand the changes to expect and if I need to upgrade to major 3

**Comment by olivervogel** [comment]
I will keep this in mind and provide release notes in the official documentation.

**Comment by olivervogel** [comment]
The only major difference when upgrading from 2.x to 3.x is that rules can no longer be passed as strings. The must be passed as objects.

See code example: https://github.com/Intervention/validation/issues/53#issuecomment-1005855807

**Comment by williamdes** [comment]
My point was, please write releases on https://github.com/Intervention/validation/releases

Thank you for everything else :)
