### ISSUE TITLE
Did you drop support for Laravel 6?

### ISSUE THREAD

**Issue by Benoit1980** [Intervention/validation#53]
Hello,

I cannot find any updates on Laravel 6, did you drop its support for Laravel 6 please?

Thank you,

**Comment by olivervogel** [comment]
All rules should still be working with Laravel 6. But please note that since version 3 it is only possible to pass the custom rules as objects and not as strings.

### Version 2 Code

```php
$validator = Validator::make($request->all(), [
    'color' => ['required', 'hexcolor'],
]);
```

### Version 3 Code

```php
$validator = Validator::make($request->all(), [
    'color' => ['required', new Hexcolor()],
]);
```

**Comment by Benoit1980** [comment]
Thank you so much @olivervogel for your kind reply :-)
