### ISSUE TITLE
Iban Validation Issue

### ISSUE THREAD

**Issue by dennisoderwald** [Intervention/validation#7]
Hello,

We are using the IBAN validation and noticed, that if we use `507008` as IBAN, it will return `true` instead of false. But since `507008` is not a valid IBAN it shouldn’t return `true`.

**Comment by olivervogel** [comment]
Thanks for reporting. Is fixed in 6141978f31d28e9e1cc543fe4b78ef3fa4ec994c.

**Comment by dennisoderwald** [comment]
Thanks @olivervogel! :+1:
