### ISSUE TITLE
isodate support timezone?

### ISSUE THREAD

**Issue by devmark** [Intervention/validation#8]
2015-09-21T19:39:41+03:00 not working

**Comment by olivervogel** [comment]
`2015-09-21 19:39:41+03:00` this is working. I have to check, what format is the `T`.

**Comment by Gummibeer** [comment]
It's the W3C format - php can handle it.
http://php.net/manual/en/class.datetime.php#datetime.constants.w3c

**Comment by olivervogel** [comment]
Working in [1.4.1](https://github.com/Intervention/validation/releases/tag/1.4.1).
