### ISSUE TITLE
Problem with some IBANs

### ISSUE THREAD

**Issue by fateme12** [Intervention/validation#86]
Hello, and thanks for the great package.

We have a problem with validating some IBANs with your package. These are some IBANs that are valid but they do not validate with your package.

IE91AIBK93419446888083
IT38N0103014217000000668829
IE92PFSR99107016194974

 Could you please check the problem and explain why this happens?

Thanks in advance

**Comment by olivervogel** [comment]
I cannot find any errors here. [The specified IBAN numbers give correct validation results](https://github.com/Intervention/validation/pull/87). Are you on the newest package version?

**Comment by fateme12** [comment]
We are using version 3.3 and we have the problem that I described.

**Comment by olivervogel** [comment]
Please update to 4.4. This should solve the issue.
